In [77]:
# DATA ENCODING
# 1) Nomial/OHE Encoding
# 2) Label and Ordinal Encoding
# 3) Target Guided Ordinal Encoding

1) Nomial/OHE encoding--- one hot encoding

In [78]:
# covert categorical data into numeric data
# use only minimum(small) data

import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [79]:
# create a simple dataframe
df=pd.DataFrame({
    'color':['red','blue','green','green','red','blue']
})

In [80]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [81]:
# create an instance of OHE
encoder=OneHotEncoder()

In [82]:
# perform fit and transform
encoded=encoder.fit_transform(df[['color']]).toarray()

In [83]:
import pandas as pd
encoder_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [84]:
encoder_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [85]:
encoder.transform([['blue']]).toarray()

/usr/local/python/3.12.1/lib/python3.12/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])

In [86]:
pd.concat([df,encoder_df],axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0
5   blue         1.0          0.0        0.0

2.Label and Ordinal Encoding

In [87]:
# label encoder
# convert categorical data into numeric data
# give rank label

In [88]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [89]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder=LabelEncoder()

In [90]:
lbl_encoder.fit_transform(df[['color']])

/usr/local/python/3.12.1/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 1, 1, 2, 0])

In [91]:
lbl_encoder.transform([['red']])

/usr/local/python/3.12.1/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([2])

In [92]:
lbl_encoder.transform([['blue']])

/usr/local/python/3.12.1/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([0])

In [93]:
lbl_encoder.transform([['green']])

/usr/local/python/3.12.1/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([1])

In [94]:
# ordinal encoder
# convert categorical data into numeric data

In [95]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder

In [96]:
df= pd.DataFrame({
    'size':['small','medium','large','medium','small','large']
})

In [97]:
df

     size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [98]:
## craete an instance of OrdinalEncoder and then fit_transform
encoder=OrdinalEncoder(categories=[['small','medium','large']])

In [99]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [100]:
encoder.transform([['small']])

/usr/local/python/3.12.1/lib/python3.12/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[0.]])

3.Target Guided Ordinal Encoding

In [101]:
# used to encode categorical variables based on the relationship with the target value
# use mean and median

In [102]:
import pandas as pd

# create a sample dataframe with a categorical variable and a target variable
df= pd.DataFrame({
    'city':['new york','london','paris','tokyo','new york','paris'],
    'price':[200,150,300,250,180,320]
})

In [103]:
df

       city  price
0  new york    200
1    london    150
2     paris    300
3     tokyo    250
4  new york    180
5     paris    320

In [104]:
mean_price=df.groupby('city')['price'].mean().to_dict()

In [105]:
mean_price

{'london': 150.0, 'new york': 190.0, 'paris': 310.0, 'tokyo': 250.0}

In [106]:
df['city_encoded']=df['city'].map(mean_price)

In [107]:
df[['city','city_encoded']]

       city  city_encoded
0  new york         190.0
1    london         150.0
2     paris         310.0
3     tokyo         250.0
4  new york         190.0
5     paris         310.0